name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        override: true
        profile: minimal
        toolchain: stable
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run build
    - run: rm dist/**/{package.json,LICENSE,README.md,.gitignore}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}